### ISSUE TITLE
The problem with the mod

### ISSUE THREAD

**Issue by VladHinevich** [Jalopy-Mods/DeliveryJob#1]
Hi! Many thanks for this modification) The boxes are spawned only in Berlin, in other cities all the shops are empty (And one of the boxes had to be delivered to the hotel reception, but there was no icon at the destination. Sorry for my English, I'm using a translator

**Comment by theLeaxx** [comment]
Will look into it.

When testing, these issues hadn't occurred at all, so it's a bit awkward.

**Comment by theLeaxx** [comment]
After looking into it, I have noticed:
* The boxes "only spawning in Berlin" and "one of the boxes had to be delivered to the hotel reception, but there was no icon at the destination" are not bugs, they're intended features. The boxes are intended to be picked up & delivered at night, **BEFORE** sleeping at the motel
* The boxes "only spawning in Berlin" was something that could happen sometimes, but most likely not your case.
